global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: checkout
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['checkout:8080']
  - job_name: payment
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['payment:8080']
